# Generated by Django 4.0.4 on 2022-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessinfo',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=45, null=True)),
                ('week', models.CharField(blank=True, db_column='Week', max_length=20, null=True)),
                ('estimated_load_date', models.DateField(blank=True, db_column='Estimated_Load_Date', null=True)),
                ('pre_etd', models.DateField(blank=True, db_column='Pre_ETD', null=True)),
                ('etd', models.DateField(blank=True, db_column='ETD', null=True)),
                ('eta', models.DateField(blank=True, db_column='ETA', null=True)),
                ('vessel_voyage', models.CharField(db_column='Vessel_Voyage', max_length=45)),
                ('pol', models.CharField(db_column='POL', max_length=20)),
                ('pod', models.CharField(db_column='POD', max_length=20)),
                ('businessinfocol', models.CharField(blank=True, db_column='BusinessInfocol', max_length=200, null=True)),
                ('numctrs', models.IntegerField(db_column='NumCtrs')),
                ('type_ctrs', models.CharField(db_column='Type_Ctrs', max_length=10)),
                ('booking_no', models.CharField(db_column='Booking_No', max_length=45)),
                ('master_no', models.CharField(blank=True, db_column='Master_No', max_length=45, null=True)),
                ('first_hbl_no', models.CharField(blank=True, db_column='First_Hbl_No', max_length=45, null=True)),
                ('hbl_memo', models.CharField(blank=True, db_column='Hbl_Memo', max_length=45, null=True)),
                ('num_hbls', models.IntegerField(blank=True, db_column='Num_HBLs', null=True)),
                ('container_no', models.CharField(blank=True, db_column='Container_No', max_length=45, null=True)),
                ('shipping_line', models.CharField(db_column='Shipping_Line', max_length=20)),
                ('freeddday', models.IntegerField(db_column='FreeDDday')),
                ('cost_org', models.FloatField(blank=True, db_column='Cost_Org', null=True)),
                ('sale_org', models.FloatField(blank=True, db_column='Sale_Org', null=True)),
                ('set_org', models.FloatField(blank=True, db_column='Set_Org', null=True)),
                ('local_org', models.FloatField(blank=True, db_column='Local_Org', null=True)),
                ('venta_dest', models.FloatField(blank=True, db_column='Venta_Dest', null=True)),
                ('costhbl_dest_description', models.CharField(blank=True, db_column='CostHBL_Dest_Description', max_length=45, null=True)),
                ('costhbl_dest', models.FloatField(blank=True, db_column='CostHBL_Dest', null=True)),
                ('costhbl_dest_status', models.CharField(db_column='CostHBL_Dest_Status', max_length=10)),
                ('topaid_org_description', models.CharField(blank=True, db_column='Topaid_Org_Description', max_length=45, null=True)),
                ('topaid_org', models.FloatField(blank=True, db_column='Topaid_Org', null=True)),
                ('topaid_status', models.CharField(db_column='Topaid_Status', max_length=10)),
                ('toinvoice_dest_description', models.CharField(blank=True, db_column='ToInvoice_Dest_Description', max_length=45, null=True)),
                ('toinvoice_dest', models.FloatField(blank=True, db_column='ToInvoice_Dest', null=True)),
                ('toinvoice_dest_status', models.CharField(db_column='ToInvoice_Dest_Status', max_length=10)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('hbl_canjeado_status', models.CharField(db_column='HBL_Canjeado_Status', max_length=10)),
                ('devolution_ctrs_inidate', models.DateField(blank=True, db_column='Devolution_Ctrs_IniDate', null=True)),
                ('devolution_ctrs_findate', models.DateField(blank=True, db_column='Devolution_Ctrs_FinDate', null=True)),
                ('operation_status', models.CharField(db_column='Operation_Status', max_length=10)),
                ('bl_type', models.CharField(blank=True, db_column='BL_Type', max_length=3, null=True)),
                ('release_type', models.CharField(blank=True, db_column='Release_Type', max_length=45, null=True)),
                ('mblfile', models.FileField(blank=True, db_column='MBLFile', null=True, upload_to='MBLs-%Y%m/')),
                ('hblfiles', models.FileField(blank=True, db_column='HBLFiles', null=True, upload_to='HBLs-%Y%m/')),
                ('dp_voucher', models.FileField(blank=True, db_column='DP_Voucher', null=True, upload_to='DPVs-%Y%m/')),
                ('dp_invoice', models.FileField(blank=True, db_column='DP_Invoice', null=True, upload_to='DPIs-%Y%m/')),
                ('hp_voucher', models.FileField(blank=True, db_column='HP_Voucher', null=True, upload_to='HPVs-%Y%m/')),
                ('hp_invoice', models.FileField(blank=True, db_column='HP_Invoice', null=True, upload_to='HPIs-%Y%m/')),
                ('hbls_canjeados', models.FileField(blank=True, db_column='HBLs_Canjeados', null=True, upload_to='HBLCNJDs-%Y%m/')),
                ('income_voucher', models.FileField(blank=True, db_column='Income_Voucher', null=True, upload_to='INVs-%Y%m/')),
                ('income_invoice', models.FileField(blank=True, db_column='Income_Invoice', null=True, upload_to='INI-%Y%m/')),
                ('hbls_firmados', models.FileField(blank=True, db_column='HBLs_Firmados', null=True, upload_to='HBLCFRMDs-%Y%m/')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInfo',
            fields=[
                ('id', models.CharField(db_column='id', max_length=45, primary_key=True, serialize=False)),
                ('clientname', models.CharField(db_column='ClientName', max_length=45)),
                ('clientrut', models.CharField(db_column='ClientRut', max_length=20)),
                ('clientgiro', models.CharField(db_column='ClientGiro', max_length=200)),
                ('clientaddress', models.CharField(db_column='ClientAddress', max_length=200)),
                ('clientcity', models.CharField(db_column='ClientCity', max_length=45)),
                ('clientstate', models.CharField(db_column='ClientState', max_length=45)),
                ('clientcontact', models.CharField(db_column='ClientContact', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
